'use client';
import {useEffect,useRef,useState} from 'react';
import {Upload,RefreshCw,Download,Link2,Check,FileText,Pause,Copy} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {parseLinks,Row,isValidToken} from '@/lib/links';
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
export default function Home(){
 const [text,setText]=useState(''),[rows,setRows]=useState<Row[]>([]),[duplicates,setDuplicates]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[filename,setFilename]=useState(''),[drag,setDrag]=useState(false),[page,setPage]=useState(0);
 const [mode,setMode]=useState('direct'),[directRows,setDirectRows]=useState<{id:number;url:string;expiresAt:string}[]>([]);
 const stop=useRef(false),running=useRef(false),fileInput=useRef<HTMLInputElement>(null),latest=useRef(rows);latest.current=rows;
 const success=rows.filter(r=>r.status==='success'),fail=rows.filter(r=>['invalid','error'].includes(r.status)),pending=rows.filter(r=>r.status==='queued'),done=success.length+fail.length;
 function load(value:string){if(running.current)return;const parsed=parseLinks(value);if(parsed.rows.length>10000){setNotice('Use up to 10,000 links per batch.');return;}setText(value);setRows(parsed.rows);setDirectRows([]);setDuplicates(parsed.duplicates);setPage(0);setNotice('');}
 async function readFile(file?:File){if(!file)return;if(!file.name.toLowerCase().endsWith('.txt')){setNotice('Please choose a .txt file.');return;}if(file.size>5*1024*1024){setNotice('The file must be smaller than 5 MB.');return;}try{load(await file.text());setFilename(file.name);}catch{setNotice('Could not read this file.');}}
 function update(id:number,changes:Partial<Row>){setRows(old=>old.map(r=>r.id===id?{...r,...changes}:r));}
 async function run(retry=false){if(running.current)return;const queue=latest.current.filter(r=>r.status==='queued'||(retry&&r.status==='error'));if(!queue.length)return;running.current=true;stop.current=false;setBusy(true);setNotice('Refreshing your links… Keep this tab open.');
 try {for(const row of queue){if(stop.current)break;update(row.id,{status:'refreshing',message:undefined});let completed=false;
 for(let attempt=0;attempt<3;attempt++){
 if(stop.current){update(row.id,{status:'queued'});break;}
 try {const response=await fetch('/api/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:row.token}),signal:AbortSignal.timeout(70000)});const raw=await response.text();let data:{status?:string;url?:string;message?:string};try{data=JSON.parse(raw);}catch{update(row.id,{status:'error',message:response.status===401||response.status===403?'Session expired or access denied. Open the app in a new tab and enter your admin login.':`App returned HTTP ${response.status} instead of an API response. Open the app in a new tab and retry.`});stop.current=true;setNotice('App session or request error. Open the app in a new tab and retry.');completed=true;break;}
 if(response.status===429&&attempt<2){setNotice('Supplier rate limit reached. Retrying in 60 seconds…');for(let i=0;i<60&&!stop.current;i++)await sleep(1000);continue;}
 if(response.ok&&data.status==='success'){update(row.id,{status:'success',url:data.url});}
 else {update(row.id,{status:response.status===404?'invalid':'error',message:data.message||'Refresh failed'});if(response.status===401||response.status===503){stop.current=true;setNotice(data.message||'API request failed.');}}
 completed=true;break;
 }catch(error){const e=error as Error;update(row.id,{status:'error',message:e.name==='TimeoutError'||e.name==='AbortError'?'Request timed out after 70 seconds. Retry this link.':'Browser could not connect to the app. Open it in a new tab and retry.'});stop.current=true;setNotice('Connection to the app failed. Open the app in a new tab and retry.');completed=true;break;}}
 if(!completed)update(row.id,{status:'queued'});if(!stop.current){setNotice('Refreshing your links… Keep this tab open.');await sleep(850);}}
 setNotice(old=>stop.current?(old.startsWith('API')?old:'Paused. You can resume the remaining links.'):'Batch finished. Download your refreshed links below.');
 }finally{running.current=false;setBusy(false);}}
 async function createDirect(){if(running.current)return;const queue=rows.filter(r=>isValidToken(r.token)&&!directRows.some(d=>d.id===r.id));if(!queue.length)return;running.current=true;stop.current=false;setBusy(true);setNotice('Creating customer links…');try{for(let offset=0;offset<queue.length&&!stop.current;offset+=100){const batch=queue.slice(offset,offset+100);const response=await fetch('/api/direct',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tokens:batch.map(r=>r.token)}),signal:AbortSignal.timeout(40000)});let data:{status?:string;links?:{url:string;expiresAt:string}[];message?:string};try{data=await response.json() as typeof data}catch{throw Error('App session expired. Open the app in a new tab and enter your admin login.')}if(!response.ok||data.status!=='success'||!data.links||data.links.length!==batch.length)throw Error(data.message||'Could not create direct links');const added=data.links.map((d,i)=>({...d,id:batch[i].id}));setDirectRows(old=>[...old,...added]);setNotice(`${Math.min(offset+batch.length,queue.length)} customer links created.`);}setNotice(stop.current?'Paused. Create remaining links when ready.':'Customer links are ready. Supplier validation happens when a customer opens each link.');}catch(error){setNotice((error as Error).message||'Could not create direct links')}finally{running.current=false;setBusy(false);}}
 function exportDirect(report=false){const content=report?JSON.stringify(directRows.map(d=>({original:rows.find(r=>r.id===d.id)?.original,...d})),null,2):directRows.map(d=>d.url).join('\n');const url=URL.createObjectURL(new Blob([content],{type:report?'application/json':'text/plain'}));const a=document.createElement('a');a.href=url;a.download=report?'customer-links-report.json':'customer-activation-links.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function download(kind:'links'|'report'){const content=kind==='links'?success.map(r=>r.url).join('\n'):JSON.stringify(rows.map(({original,status,url,message})=>({original,status,refreshedLink:url||null,error:message||null})),null,2);const blob=new Blob([content],{type:kind==='links'?'text/plain':'application/json'}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=kind==='links'?'refreshed-links.txt':'refresh-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const controller=new AbortController();Promise.resolve(ctx.registerTool({name:'get_refresh_results',description:'Read the current link refresh batch and its results.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({results:latest.current.map(({id,status,url,message})=>({id,status,url,message}))})} ,{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
 return <main><header><div className="brand"><span className="brand-icon"><Link2 size={22}/></span>EM Store<span className="brand-divider">/</span><span className="brand-sub">Link Refresh</span></div><span className="private-label">Admin workspace</span></header>
 <div className="workspace"><div className="heading"><div><p className="eyebrow">GOOGLE ONE · GEMINI</p><h1>Activation, on opening.</h1><p>Create customer links that refresh automatically and open Google’s activation page.</p></div><span className="expiry">API access expires 29 Oct 2026</span></div>
 <Tabs value={mode} onValueChange={value=>{if(!busy){setMode(value);setNotice('');setPage(0);}}}><TabsList className="mode-tabs"><TabsTrigger value="direct" disabled={busy}>Direct customer links</TabsTrigger><TabsTrigger value="refresh" disabled={busy}>Batch refresh</TabsTrigger></TabsList><div className="grid"><section className="import-panel"><div className="section-title"><span className="step">01</span><h2>Your link list</h2></div>
 <button disabled={busy} className={'dropzone '+(drag?'drag':'')} onClick={()=>fileInput.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!busy)void readFile(e.dataTransfer.files[0])}}><Upload size={28}/><strong>{filename||'Drop your TXT file here'}</strong><span>or click to browse · up to 5 MB</span></button><input ref={fileInput} type="file" accept=".txt,text/plain" className="hidden" disabled={busy} onChange={e=>{void readFile(e.target.files?.[0]);e.target.value=''}}/>
 <label htmlFor="links">Or paste your links</label><textarea id="links" value={text} disabled={busy} onChange={e=>{setFilename('');load(e.target.value)}} placeholder={'https://serviceactivation.google.com/subscription/new/…\nhttps://serviceactivation.google.com/subscription/new/…'} spellCheck={false}/>
 <p className="hint">One full activation link or token per line. Duplicates are removed automatically.</p>
 <div className="import-meta"><span>{rows.length.toLocaleString()} unique entries</span><span>{duplicates} duplicates removed</span></div>
 <button className="primary" disabled={busy||(mode==='refresh'?!pending.length:!rows.some(r=>isValidToken(r.token)&&!directRows.some(d=>d.id===r.id)))} onClick={()=>void (mode==='direct'?createDirect():run())}>{mode==='direct'?<Link2 size={18}/>:<RefreshCw size={18}/>} {busy?(mode==='direct'?'Creating links…':'Refreshing…'):mode==='direct'?'Create customer links':done&&pending.length?'Resume refresh':'Refresh links'}</button>
 <p className="privacy-note">{mode==='direct'?'Each customer link opens for 7 days. Refresh success depends on your supplier.':'Your list stays in this tab. Only each token is sent to your supplier for refresh.'}</p></section>
 <TabsContent value="refresh"><section className="results-panel"><div className="section-title"><span className="step">02</span><h2>Batch results</h2>{busy&&<button className="small-button pause" onClick={()=>{stop.current=true;setNotice('Pausing after the current request…')}}><Pause size={14}/>Pause</button>}</div>
 <div className="stats"><div><span>Total links</span><strong>{rows.length}</strong></div><div><span>Refreshed</span><strong className="green">{success.length}</strong></div><div><span>Failed</span><strong className={fail.length?'red':''}>{fail.length}</strong></div></div>
 <div className="progress-label"><span>{busy?'Processing':done===rows.length&&rows.length?'Completed':done?'Paused':'Ready to refresh'}</span><span>{done} / {rows.length}</span></div><Progress value={rows.length?done/rows.length*100:0}/>
 <p className="batch-notice" role="status">{notice||'Requests run one at a time, with automatic rate-limit pauses.'}</p>
 <div className="result-actions"><button className="download" disabled={!success.length} onClick={()=>download('links')}><Download size={17}/>Download TXT</button><button className="small-button" disabled={!rows.length} onClick={()=>download('report')}><FileText size={16}/>Full report</button>{rows.some(r=>r.status==='error')&&!busy&&<button className="small-button" onClick={()=>void run(true)}>Retry errors</button>}</div>
 {!rows.length?<div className="empty"><span><Link2 size={32}/></span><h3>Your refreshed links will appear here</h3><p>Start with a TXT file or paste your list on the left.</p></div>:<><Table><TableHeader><TableRow><TableHead>Link</TableHead><TableHead>Status</TableHead><TableHead>Result</TableHead></TableRow></TableHeader><TableBody>{rows.slice(page*50,(page+1)*50).map(row=><TableRow key={row.id}><TableCell><div className="link-id">#{String(row.id).padStart(3,'0')}</div><div className="token-preview" title={row.original}>{(row.token||row.original).slice(0,22)}…</div></TableCell><TableCell><span className={'badge '+row.status}>{row.status==='success'?<Check size={12}/>:null}{row.status==='success'?'Refreshed':row.status==='invalid'?'Invalid':row.status==='error'?'Error':row.status==='refreshing'?'Refreshing':'Queued'}</span></TableCell><TableCell>{row.url?<button className="copy" onClick={async()=>{try{await navigator.clipboard.writeText(row.url!);setNotice(`Link #${row.id} copied.`)}catch{setNotice('Copy unavailable. Use Download TXT.')}}}><Copy size={14}/>Copy link</button>:<span className="row-message">{row.message||'—'}</span>}</TableCell></TableRow>)}</TableBody></Table><div className="pager"><span>Showing {page*50+1}–{Math.min((page+1)*50,rows.length)} of {rows.length}</span><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={(page+1)*50>=rows.length} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}
 </section></TabsContent><TabsContent value="direct"><section className="results-panel"><div className="section-title"><span className="step">02</span><h2>Customer links</h2>{busy&&<button className="small-button pause" onClick={()=>{stop.current=true;}}>Pause</button>}</div><div className="stats"><div><span>Ready to share</span><strong className="green">{directRows.length}</strong></div><div><span>Opening window</span><strong>7 days</strong></div><div><span>Excluded entries</span><strong className={rows.filter(r=>!isValidToken(r.token)).length?'red':''}>{rows.filter(r=>!isValidToken(r.token)).length}</strong></div></div><p className="batch-notice" role="status">{notice||'Customer opens the link. It refreshes automatically, then continues to Google. No reactivation key or bot button.'}</p><div className="result-actions"><button className="download" disabled={!directRows.length} onClick={()=>exportDirect()}><Download size={17}/>Download customer TXT</button><button className="small-button" disabled={!directRows.length} onClick={()=>exportDirect(true)}><FileText size={16}/>Full report</button></div>{!directRows.length?<div className="empty"><span><Link2 size={32}/></span><h3>One link to share with your customer</h3><p>Upload your list and choose Create customer links.</p></div>:<><Table><TableHeader><TableRow><TableHead>Link</TableHead><TableHead>Expires</TableHead><TableHead>Customer URL</TableHead></TableRow></TableHeader><TableBody>{directRows.slice(page*50,(page+1)*50).map(d=><TableRow key={d.id}><TableCell><span className="link-id">#{String(d.id).padStart(3,'0')}</span></TableCell><TableCell><span className="row-message">{new Date(d.expiresAt).toLocaleString()}</span></TableCell><TableCell><div className="direct-url" title={d.url}>{d.url}</div><button className="copy" onClick={async()=>{try{await navigator.clipboard.writeText(d.url);setNotice(`Customer link #${d.id} copied.`)}catch{setNotice('Copy unavailable. Use Download customer TXT.')}}}><Copy size={14}/>Copy customer link</button></TableCell></TableRow>)}</TableBody></Table><div className="pager"><span>Showing {page*50+1}–{Math.min((page+1)*50,directRows.length)} of {directRows.length}</span><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={(page+1)*50>=directRows.length} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}<p className="hint">Creating a customer link does not check or extend the Google offer. Your supplier refreshes it on opening.</p></section></TabsContent></div></Tabs><footer><span>EM Store tools</span><span>Only tokens registered with your supplier can be refreshed.</span></footer></div></main>;
}
